name: Build Release APK

on:
  workflow_dispatch:
    inputs:
      versionCode:
        type: number
        description: "Version Code"
        required: true
      versionName:
        type: string
        description: "Version Name"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "devFirebaseRepositoryPath=${{ secrets.DEV_FIREBASE_REPOSITORY_PATH }}" >> local.properties
          echo "devFirebaseStorageBucket=${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}" >> local.properties
          echo "prodFirebaseRepositoryPath=${{ secrets.PROD_FIREBASE_REPOSITORY_PATH }}" >> local.properties
          echo "prodFirebaseStorageBucket=${{ secrets.PROD_FIREBASE_STORAGE_BUCKET }}" >> local.properties

      - name: Create google-services.json
        run: |
          echo '${{ secrets.PROD_GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Inject version
        run: |
          echo "VERSION_CODE=${{ github.event.inputs.versionCode }}" >> gradle.properties
          echo "VERSION_NAME=${{ github.event.inputs.versionName }}" >> gradle.properties

      - name: Decode keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > app/release.keystore

      - name: Set signing variables
        run: |
          echo "RELEASE_KEYSTORE_FILE=release.keystore" >> $GITHUB_ENV
          echo "RELEASE_KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace -PreleaseKeystoreFile=$RELEASE_KEYSTORE_FILE

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk \
             app/build/outputs/apk/release/mejourney_release_${{ github.event.inputs.versionName }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: mejourney_release_${{ github.event.inputs.versionName }}
          path: app/build/outputs/apk/release/mejourney_release_${{ github.event.inputs.versionName }}.apk